Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 4567, host: 3000
  config.vm.synced_folder ".", "/vagrant"
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", path: 'provision.sh'
end
