Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "foo" do |node|
    node.vm.hostname = "foo"
    node.vm.network "private_network", ip: "192.168.42.42"
    config.hostmanager.aliases = ["foo.app.internal"]
  end

  config.vm.define "bar" do |node|
    node.vm.hostname = "bar"
    node.vm.network "private_network", ip: "192.168.42.43"
    config.hostmanager.aliases = ["bar.app.internal"]
  end

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", path: "provision.sh"
end
