Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # Original username password combination is admin:changeit
  # Example docker setup with eventstore.conf
  # https://github.com/EventStore/eventstore-docker
  config.vm.hostname = "eventstore"

  config.vm.network "private_network", ip: "192.168.53.53"
  config.hostmanager.aliases = ["eventstore.dev"]

  config.vm.provision "shell",
  path: "provision.sh"
end
